version: 2

jobs:
  plan-apply:
    working_directory: /terraform/solutions/application
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            cd terraform/solutions/application
            terraform init -input=false -backend-config=bucket=web-app-terraform-state-dev
            terraform workspace select dev
            terraform plan -out tfapply -var-file ../../environments/application/dev.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-apply
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-apply
      - plan-destroy:
          requires:
            - apply
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
      - destroy:
          requires:
            - hold-destroy